name: Deploy to Permaweb
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install
        
      - name: Deploy to Permaweb
        run: bun run deploy-main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 